In [1]:
### Tutorial from: https://www.hackerearth.com/practice/machine-learning/data-manipulation-visualisation-r-python/tutorial-data-manipulation-numpy-pandas-python/tutorial/ ###

import numpy as np

In [ ]:
# Create a list comprising numbers (integers) from 0 to 9
## recall that a list and an array are similar because they are both used to store any data type (numbers, strings, etc.), they can both be indexed and iterated through.
## main diff between a list and an array is the functions that you can perform on them.
## arrays must be declared; arrays are used when you want to perform arithmetic functions to lists
## arrays will store data more compactly
## ex. list: y = [3, 6, 9, 12]
## ex. array: x = array([3, 6, 9, 12])

L = list(range(10))

In [3]:
# Perform list comprehension by converting integers to string (str)

[str(c) for c in L]

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [4]:
[type(item) for item in L]

[int, int, int, int, int, int, int, int, int, int]

In [5]:
# Create an array. Numpy arrays are homogenous - they comprise one daa type (integer, float, double, string, etc), unlike lists (which can have multiple data types).

np.zeros(10, dtype = 'int')


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [6]:
# Create a 3 row by 5 column matrix array.

np.ones((3,5), dtype = float)


array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [7]:
# Create a matrix with a predefined value.

np.full((3,5), 1.23)


array([[1.23, 1.23, 1.23, 1.23, 1.23],
       [1.23, 1.23, 1.23, 1.23, 1.23],
       [1.23, 1.23, 1.23, 1.23, 1.23]])

In [10]:
# Create an array with a set sequence.

np.arange(0, 20 , 2) # note spelling of 'arange'; this says to create an array spanning 0 to 20 in increments of 2.

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [11]:
# Create an array of even space between the given range of values

np.linspace(0, 1, 5) # span 0 to 1 with 5 equal increments.

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [12]:
# Create a 3 X 3 array with mean 0 and standard deviation 1 in a given dimension.

np.random.normal(0, 1, (3,3))


array([[-0.18381118, -2.03950073,  0.4136133 ],
       [ 0.8091768 ,  0.00778174, -0.26642328],
       [-0.68789707, -0.39708178,  0.9410211 ]])

In [13]:
# Create an identity matrix. A square matrix in which the elements of the principal diagonal are ones and all other elements are zeros. The effect of multiplying a given matrix by an identity matrix is to leave the given matrix unchanged.

np.eye(3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
# Set a random seed

np.random.seed(0)

In [15]:
x1 = np.random.randint(10, size=6) # one dimension
x2 = np.random.randint(10, size=(3,4)) # two dimension
x3 = np.random.randint(10, size=(3,4,5)) # three dimension

In [17]:
x1

array([5, 0, 3, 3, 7, 9])

In [18]:
print(x1)

[5 0 3 3 7 9]


In [19]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [20]:
x3

array([[[8, 1, 5, 9, 8],
        [9, 4, 3, 0, 3],
        [5, 0, 2, 3, 8],
        [1, 3, 3, 3, 7]],

       [[0, 1, 9, 9, 0],
        [4, 7, 3, 2, 7],
        [2, 0, 0, 4, 5],
        [5, 6, 8, 4, 1]],

       [[4, 9, 8, 1, 1],
        [7, 9, 9, 3, 6],
        [7, 2, 0, 3, 5],
        [9, 4, 4, 6, 4]]])

In [22]:
print("x3 ndim:", x3.ndim)

x3 ndim: 3


In [23]:
print("x3 shape:", x3.shape)

x3 shape: (3, 4, 5)


In [24]:
print("x3 size:", x3.size)

x3 size: 60


In [25]:
# Array indexing: REMEMBER! Indexing in python starts at ZERO.

x1 = np.array([4, 3, 4, 4, 8, 4])
x1

array([4, 3, 4, 4, 8, 4])

In [26]:
# Assess value to index zero
x1[0]

4

In [27]:
# Assess fifth value
x1[4]

8

In [28]:
# Get last value
x1[-1]

4

In [29]:
# Get the second to last value
x1[-2]

8

In [30]:
# In a multidimensional array, we must specify row and column index.
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [31]:
# Index the 0 ,1, *2* row and 0, 1, 2, *3* column.
x2[2,3]

7

In [32]:
# Index the 3rd row and last value from the third column.
x2[2,-1]

7

In [33]:
# Replace the value at 0,0 index with a new value.
x2[0,0] = 12
x2


array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [34]:
# Replace the value at 2,3 with a new value.
x2[2,3] = 20
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7, 20]])

In [35]:
# Replace the value at 2,-1 with a new value.
x2[2,-1] = 55
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7, 55]])

In [36]:
# Array slicing. Access multiple or a range of elements from an array.

x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
# Slice this array, x, from the start of it to the 4th position (0, 1, 2, 3, 4).
x[:5]

array([0, 1, 2, 3, 4])

In [38]:
# Slice the same array, x, from the 4th position to the end of the array.
x[4:]

array([4, 5, 6, 7, 8, 9])

In [39]:
# Slice from the 4th to the 6th position
x[4:7]

array([4, 5, 6])

In [40]:
# Return elements in the array, x, at even places only.
x[ : : 2]


array([0, 2, 4, 6, 8])

In [41]:
# Return elements from the first position in the array, x, onward, and step by 2 each time.
x[1::2]

array([1, 3, 5, 7, 9])

In [42]:
# Reverse the order of the array
x[::-1] # whole array, by -1


array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [43]:
# Array concatenation (combining arrays). Instead of typing elements manually, you can use concatenation.

# Concatenate 2 or more arrays at once.

x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
z = [21, 21, 21]
np.concatenate([x, y, z])


array([ 1,  2,  3,  3,  2,  1, 21, 21, 21])

In [44]:
# Use the concatenate function to create 2D arrays.
grid = np.array([[1, 2, 3], [4, 5, 6]])
np.concatenate([grid, grid])


array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [45]:
# Using its axis parameter, you can define either a row-wise or column-wise matrix.

np.concatenate([grid, grid], axis = 1)


array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [47]:
# What happens if axis = 2? # this throws an error. specifying axis = 0 however, which appears to be the default, makes the grids arrange on top of each other. 4 rows 3 columns.
# specifying axis = 1 creates a row-wise matrix, 2 rows, 6 columns.

np.concatenate([grid, grid], axis = 0)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [48]:
# What if you are required to compbine a 2D array with a 1D array? In this case np.concatenate might not be the best option.
# To combine arrays with different dimensions, use np.vstack or np.hstack.

x = np.array([3, 4, 5])
grid = np.array([[1, 2, 3], [17, 18, 19]])

np.vstack([x, grid]) # v stands for vertical stacking


array([[ 3,  4,  5],
       [ 1,  2,  3],
       [17, 18, 19]])

In [50]:
# Now try with np.hstack. This threw an error!

# np.hstack([x, grid])

In [51]:
# Try defining different arrays to combine with np.hstack

z = np.array([[9], [9]]) 
np.hstack([grid, z])   # h stands for horizontal stacking

array([[ 1,  2,  3,  9],
       [17, 18, 19,  9]])

In [53]:
# Split arrays based on pre-defined positions.

x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
x1, x2, x3 = np.split(x,[3,6]) # split the above defined array x into 3 arrays, x1, x2, and x3, and split them at position 3 and position 6.
print(x1, x2, x3)

[0 1 2] [3 4 5] [6 7 8 9]


In [57]:
# Try again with different split - here one split at 4th position.

x4, x5 = np.split(x,[4])
print(x4, x5)

[0 1 2 3] [4 5 6 7 8 9]


In [59]:
# Try another split

grid = np.arange(16).reshape((4,4)) # make an array of 16 positions 0 - 15, and then reshape the array into a 4 X 4 matrix.
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [60]:
upper, lower = np.vsplit(grid, [2]) # vertical, but this seems to be horizontal?
print(upper, lower) # this creates two arrays out of one array - notice the bracketing.

[[0 1 2 3]
 [4 5 6 7]] [[ 8  9 10 11]
 [12 13 14 15]]


In [61]:
upper2, lower2 = np.hsplit(grid, [2]) # horizontal but seems to be a vertical split of grid?
print(upper2, lower2)
# see documentation https://docs.scipy.org/doc/numpy/reference/generated/numpy.hsplit.html

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]] [[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [69]:
# There are several other mathematical functions available in the numpy library such as:
## sum, divide, multiply, abs, power, mod, sin, cos, tan, log, var, min, mean, max, etc.
## refer to numpy documentation for more information on such functions

## see this link: https://docs.scipy.org/doc/numpy-1.13.0/reference/routines.math.html

In [70]:
# Let's start with Pandas! 
## load library

import pandas as pd


In [72]:
# Create a new data frame - dictionary is used here where keys get converted to clumn names and values to row values.

data = pd.DataFrame({'Country': ['Russia', 'Columbia', 'Chile', 'Equador', 'Nigeria'], 'Rank': [121, 40, 100, 130, 11]})
data

Country  Rank
0    Russia   121
1  Columbia    40
2     Chile   100
3   Equador   130
4   Nigeria    11

In [73]:
# Do a quick analysis of any data set using:

data.describe() # essentially summary stats of integer/double variables.

Rank
count    5.000000
mean    80.400000
std     52.300096
min     11.000000
25%     40.000000
50%    100.000000
75%    121.000000
max    130.000000

In [75]:
# To get the complete infromation about the data set we can use the info() function.

data.info() # this is like getting structure/str in R


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 2 columns):
Country    5 non-null object
Rank       5 non-null int64
dtypes: int64(1), object(1)
memory usage: 160.0+ bytes


In [76]:
# Create another data frame:

data = pd.DataFrame({'group': ['a', 'a', 'a', 'b', 'b', 'b', 'c', 'c', 'c'], 'ounces': [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})
data

group  ounces
0     a     4.0
1     a     3.0
2     a    12.0
3     b     6.0
4     b     7.5
5     b     8.0
6     c     3.0
7     c     5.0
8     c     6.0

In [77]:
# Sort this new data frame, called data, by ounces - inplace = TRUE will make changes to the data

data.sort_values(by = ['ounces'], ascending = True, inplace = False)


group  ounces
1     a     3.0
6     c     3.0
0     a     4.0
7     c     5.0
3     b     6.0
8     c     6.0
4     b     7.5
5     b     8.0
2     a    12.0

In [78]:
# Sort  by multiple columns:

data.sort_values(by = ['group','ounces'], ascending = [True, False], inplace = False)


group  ounces
2     a    12.0
0     a     4.0
1     a     3.0
5     b     8.0
4     b     7.5
3     b     6.0
8     c     6.0
7     c     5.0
6     c     3.0

In [79]:
# Often we get data sets with duplicate rows, which could be noise. We need to sometimes get rid of inconsistencies in the data set.
# To remove duplicate rows:

## First create another data frame with duplicated rows:

data = pd.DataFrame({'k1': ['one']*3 + ['two']*4, 'k2': [3, 2, 1, 3, 3, 4, 4]})
data

k1  k2
0  one   3
1  one   2
2  one   1
3  two   3
4  two   3
5  two   4
6  two   4

In [80]:
# Sort values

data.sort_values(by = 'k2')

k1  k2
2  one   1
1  one   2
0  one   3
3  two   3
4  two   3
5  two   4
6  two   4

In [81]:
# Remove duplicates

data.drop_duplicates() # this removes duplicates based on matching row values across all columns.

k1  k2
0  one   3
1  one   2
2  one   1
3  two   3
5  two   4

In [82]:
# Remove duplicates based on a particular column (k1):

data.drop_duplicates(subset = 'k1')


k1  k2
0  one   3
3  two   3

In [83]:
# Categorize rows based on a predefined critera. For example creating a new variable 'continent', based on country names in an existing column.

data = pd.DataFrame({'food': ['bacon', 'pulled pork', 'bacon', 'Pastrami', 'corned beef', 'Bacon', 'pastrami', 'honey ham', 'nova lox'], 'ounces': [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     Pastrami     6.0
4  corned beef     7.5
5        Bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [84]:
# Create a new varible which indicates the type of animal that is the source of the food. 
# First create a dictionary to map the food to the animals.
# Then use map function to map the dictionary's values to the keys.

meat_to_animal = {'bacon': 'pig', 'pulled pork': 'pig', 'pastrami': 'cow', 'corned beef': 'cow', 'honey ham': 'pig', 'nova lox': 'salmon'}

def meat_2_animal(series):
    if series['food'] == 'bacon':
        return 'pig'
    elif series['food'] == 'pulled pork':
        return 'pig'
    elif series['food'] == 'pastrami':
        return 'cow'
    elif series['food'] == 'corned beef':
        return 'cow'
    elif series['food'] == 'honey ham':
        return 'pig'
    else:
        return 'salmon'
    

In [85]:
# Create the new variable 

data['animal'] = data['food'].map(str.lower).map(meat_to_animal)
data

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     Pastrami     6.0     cow
4  corned beef     7.5     cow
5        Bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [90]:
# another way of doing the same thing is to convert the food values to the lower case and then apply the function created above (meat_2_food)

lower = lambda x: x.lower()
data['food'] = data['food'].apply(lower)
data

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     pastrami     6.0     cow
4  corned beef     7.5     cow
5        bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [91]:
data['animal2'] = data.apply(meat_2_animal, axis = 'columns')
data

food  ounces  animal animal2
0        bacon     4.0     pig     pig
1  pulled pork     3.0     pig     pig
2        bacon    12.0     pig     pig
3     pastrami     6.0     cow     cow
4  corned beef     7.5     cow     cow
5        bacon     8.0     pig     pig
6     pastrami     3.0     cow     cow
7    honey ham     5.0     pig     pig
8     nova lox     6.0  salmon  salmon

In [92]:
# Another way to create a new variable is by using the assign function. 

data.assign(new_variable = data['ounces']*10)


food  ounces  animal animal2  new_variable
0        bacon     4.0     pig     pig          40.0
1  pulled pork     3.0     pig     pig          30.0
2        bacon    12.0     pig     pig         120.0
3     pastrami     6.0     cow     cow          60.0
4  corned beef     7.5     cow     cow          75.0
5        bacon     8.0     pig     pig          80.0
6     pastrami     3.0     cow     cow          30.0
7    honey ham     5.0     pig     pig          50.0
8     nova lox     6.0  salmon  salmon          60.0

In [93]:
# Remove the "animal2" column from the data frame:

data.drop('animal2', axis = 'columns', inplace=True)
data

# see this link for inplace = True versus inplace = False (default):https://www.ritchieng.com/pandas-inplace-parameter/
# another great link with examples: https://dataconomy.com/2015/03/14-best-python-pandas-features/

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     pastrami     6.0     cow
4  corned beef     7.5     cow
5        bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [94]:
# We frequently find missing values in our data set. A quick method for imputing missing values is by filling the missing value with any random number. Not just missing values, you may find lots of outliers in your data set, which might require replacing. Let's see how we can replace values.

# Series function from pandas are used to create arrays (as with np.array).
## so in effect, a pandas series is a numpy array.

data = pd.Series([1., -999., 2., -999., -1000., 3.])
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [95]:
# Now replace the -999 values with NaN values

data.replace(-999, np.nan, inplace=True)
data

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [96]:
# Can also replace multiple values at once 

data = pd.Series([1., -999., 2., -999., -1000., 3.])
data.replace([-999, -1000], np.nan, inplace = True)
data

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [97]:
# Let's learn how to rename column names and axes (row names):

data = pd.DataFrame(np.arange(12).reshape((3,4)), index = ['Ohio', 'Colorado', 'New York'], columns = ['one', 'two', 'three', 'four'])
data


one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [98]:
# Using the rename function

data.rename(index = {'Ohio': 'SanF'}, columns = {'one': 'one_p', 'two': 'two_p'}, inplace = True)
data

one_p  two_p  three  four
SanF          0      1      2     3
Colorado      4      5      6     7
New York      8      9     10    11

In [99]:
# You can also use string functions

data.rename(index = str.upper, columns = str.title, inplace = True)
data

One_P  Two_P  Three  Four
SANF          0      1      2     3
COLORADO      4      5      6     7
NEW YORK      8      9     10    11

In [103]:
# Next we will learn to categorize/bin continuous variables. 

ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]

# We will divide ages into bins such as 18 - 25, 26 - 35, 36 - 60 and 60+

# Understand that the output - '(' means that the value is included in the bin and '[' means that the value is excluded!

bins = [18, 25, 35, 60, 100]
cats = pd.cut(ages, bins)
cats

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [101]:
# To include the right bin value, we can do:

pd.cut(ages,bins, right = False)


[[18, 25), [18, 25), [25, 35), [25, 35), [18, 25), ..., [25, 35), [60, 100), [35, 60), [35, 60), [25, 35)]
Length: 12
Categories (4, interval[int64]): [[18, 25) < [25, 35) < [35, 60) < [60, 100)]

In [107]:
# Pandas library intrinsically assigns an encoding to categorical variables.

 # cats.labels # this threw an error

In [108]:
# Let's check how many observations fall under each bin

pd.value_counts(cats)


(18, 25]     5
(35, 60]     3
(25, 35]     3
(60, 100]    1
dtype: int64

In [109]:
# We can also pass a unique name to each label

bin_names = ['Youth', 'YoungAdult', 'MiddleAge', 'Senior']
new_cats = pd.cut(ages, bins, labels = bin_names)
new_cats

[Youth, Youth, Youth, YoungAdult, Youth, ..., YoungAdult, Senior, MiddleAge, MiddleAge, YoungAdult]
Length: 12
Categories (4, object): [Youth < YoungAdult < MiddleAge < Senior]

In [110]:
pd.value_counts(new_cats)

Youth         5
MiddleAge     3
YoungAdult    3
Senior        1
dtype: int64

In [111]:
# We can also calculate their cumulative sum

pd.value_counts(new_cats).cumsum()


Youth          5
MiddleAge      8
YoungAdult    11
Senior        12
dtype: int64

In [112]:
# Proceed to learn about grouping data and creating pivots in pandas. It's an important data analysis method.

df = pd.DataFrame({'key1' : ['a', 'a', 'b', 'b', 'a'],
                  'key2' : ['one', 'two', 'one', 'two', 'one'],
                  'data1' : np.random.randn(5),
                  'data2' : np.random.randn(5)})
df

key1 key2     data1     data2
0    a  one  1.254414  1.149076
1    a  two  1.419102 -1.193578
2    b  one -0.743856  1.141042
3    b  two -2.517437  1.509445
4    a  one -1.507096  1.067775

In [114]:
# Now calculate the mean of the data1 column by key1

grouped = df['data1'].groupby(df['key1'])
grouped.mean()


key1
a    0.388807
b   -1.630647
Name: data1, dtype: float64

In [115]:
# Now let's see how to slice the data frame.

dates = pd.date_range('20130101', periods = 6)
dates


DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')

In [116]:
df = pd.DataFrame(np.random.randn(6,4),index = dates, columns = list('ABCD'))
df # 6 rows and 4 columns, populate with random numbers and add A-D new columns to 'dates'


A         B         C         D
2013-01-01 -0.686589  0.014873 -0.375666 -0.038224
2013-01-02  0.367974 -0.044724 -0.302375 -2.224404
2013-01-03  0.724006  0.359003  1.076121  0.192141
2013-01-04  0.852926  0.018357  0.428304  0.996278
2013-01-05 -0.491150  0.712678  1.113340 -2.153675
2013-01-06 -0.416111 -1.070897  0.221139 -1.123057

In [117]:
# Get first n rows from the data frame

df[:3]

A         B         C         D
2013-01-01 -0.686589  0.014873 -0.375666 -0.038224
2013-01-02  0.367974 -0.044724 -0.302375 -2.224404
2013-01-03  0.724006  0.359003  1.076121  0.192141

In [119]:
# OR

df.head(3)

A         B         C         D
2013-01-01 -0.686589  0.014873 -0.375666 -0.038224
2013-01-02  0.367974 -0.044724 -0.302375 -2.224404
2013-01-03  0.724006  0.359003  1.076121  0.192141

In [120]:
# Try 

df.head() # gives first 5

A         B         C         D
2013-01-01 -0.686589  0.014873 -0.375666 -0.038224
2013-01-02  0.367974 -0.044724 -0.302375 -2.224404
2013-01-03  0.724006  0.359003  1.076121  0.192141
2013-01-04  0.852926  0.018357  0.428304  0.996278
2013-01-05 -0.491150  0.712678  1.113340 -2.153675

In [121]:
# Slice based on date range
df['20130101': '20130104']


A         B         C         D
2013-01-01 -0.686589  0.014873 -0.375666 -0.038224
2013-01-02  0.367974 -0.044724 -0.302375 -2.224404
2013-01-03  0.724006  0.359003  1.076121  0.192141
2013-01-04  0.852926  0.018357  0.428304  0.996278

In [122]:
# Slice based on column names 
df.loc[:,['A','B']]

A         B
2013-01-01 -0.686589  0.014873
2013-01-02  0.367974 -0.044724
2013-01-03  0.724006  0.359003
2013-01-04  0.852926  0.018357
2013-01-05 -0.491150  0.712678
2013-01-06 -0.416111 -1.070897

In [123]:
# Slicing based on both row index labels and column names

df.iloc[3] # this will return the 4th row (index is 3rd)


A    0.852926
B    0.018357
C    0.428304
D    0.996278
Name: 2013-01-04 00:00:00, dtype: float64

In [124]:
# Return a specific range of rows

df.iloc[2:4, 0:2]


A         B
2013-01-03  0.724006  0.359003
2013-01-04  0.852926  0.018357

In [125]:
# Return specific rows and columns using lists containing columns or row indexes

df.iloc[[1,5], [0,2]]

A         C
2013-01-02  0.367974 -0.302375
2013-01-06 -0.416111  0.221139

In [130]:
# We can also do boolean indexing based on column values. This helps in filtering a data set based on a pre-defined condition.

df[df.A > 0.5]


A         B         C         D
2013-01-03  0.724006  0.359003  1.076121  0.192141
2013-01-04  0.852926  0.018357  0.428304  0.996278

In [131]:
# We can copy the data set

df2 = df.copy()

# And add another column
df2['E'] = ['one', 'one', 'two', 'three', 'four', 'three']
df2

A         B         C         D      E
2013-01-01 -0.686589  0.014873 -0.375666 -0.038224    one
2013-01-02  0.367974 -0.044724 -0.302375 -2.224404    one
2013-01-03  0.724006  0.359003  1.076121  0.192141    two
2013-01-04  0.852926  0.018357  0.428304  0.996278  three
2013-01-05 -0.491150  0.712678  1.113340 -2.153675   four
2013-01-06 -0.416111 -1.070897  0.221139 -1.123057  three

In [132]:
# Select rows based on column values
## This will be VERY HELPFUL!

df2[df2['E'].isin(['two', 'four'])]


A         B         C         D     E
2013-01-03  0.724006  0.359003  1.076121  0.192141   two
2013-01-05 -0.491150  0.712678  1.113340 -2.153675  four

In [133]:
# Select all rows except those with two or four

df2[~df2['E'].isin(['two', 'four'])]

A         B         C         D      E
2013-01-01 -0.686589  0.014873 -0.375666 -0.038224    one
2013-01-02  0.367974 -0.044724 -0.302375 -2.224404    one
2013-01-04  0.852926  0.018357  0.428304  0.996278  three
2013-01-06 -0.416111 -1.070897  0.221139 -1.123057  three

In [134]:
# List all columns where A is greater than C

df.query('A > C')


A         B         C         D
2013-01-02  0.367974 -0.044724 -0.302375 -2.224404
2013-01-04  0.852926  0.018357  0.428304  0.996278

In [136]:
# Using the OR condition:

df.query('A < B | C > A')


A         B         C         D
2013-01-01 -0.686589  0.014873 -0.375666 -0.038224
2013-01-03  0.724006  0.359003  1.076121  0.192141
2013-01-05 -0.491150  0.712678  1.113340 -2.153675
2013-01-06 -0.416111 -1.070897  0.221139 -1.123057

In [137]:
# But, can you select this query to become a new, subsetted data frame?

# YES.

query1 = df.query('A < B | C > A')
query1

A         B         C         D
2013-01-01 -0.686589  0.014873 -0.375666 -0.038224
2013-01-03  0.724006  0.359003  1.076121  0.192141
2013-01-05 -0.491150  0.712678  1.113340 -2.153675
2013-01-06 -0.416111 -1.070897  0.221139 -1.123057

In [138]:
type(query1)

pandas.core.frame.DataFrame

In [139]:
type(df)

pandas.core.frame.DataFrame

In [140]:
# Pivot tables are useful in analyzing dat ausing customized tabular format. 

# create a data frame

data = pd.DataFrame({'group': ['a', 'a', 'a', 'b', 'b', 'b', 'c', 'c', 'c'],
                    'ounces': [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})
data

group  ounces
0     a     4.0
1     a     3.0
2     a    12.0
3     b     6.0
4     b     7.5
5     b     8.0
6     c     3.0
7     c     5.0
8     c     6.0

In [141]:
# Calculate the means of each group

data.pivot_table(values = 'ounces', index = 'group', aggfunc = np.mean)


ounces
group          
a      6.333333
b      7.166667
c      4.666667

In [142]:
# Calculate counts by group

# another useful link: https://pandas.pydata.org/pandas-docs/stable/generated/pandas.pivot_table.html

data.pivot_table(values = 'ounces', index = 'group', aggfunc = 'count')


ounces
group        
a           3
b           3
c           3

In [144]:
# You can calculate multiple summary stats on the groups
# keep in mind that "data" is the name of the dataframe, here!!! this could be anything.

table = data.pivot_table(values = 'ounces', index = 'group', aggfunc = [min, max, np.mean])
table

# based on the link in chunk 142, it seems you can apply different aggfunc to different indexed or named columns!

min    max      mean
      ounces ounces    ounces
group                        
a        3.0   12.0  6.333333
b        6.0    8.0  7.166667
c        3.0    6.0  4.666667